name: Hello Action #1
# run-name: Hello Github Action
on: 
  workflow_dispatch:

jobs:
  echo_commend:
      runs-on: ubuntu-24.04
      steps:
        - run: echo "Hello World aka Hello Github Actions"
