name: Hello Action #1
run-name: Hello Github Action
on: 
    workflow_dispatch:
        
jobs:
    Echo-Commend:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World aka Hello Github Actions"
